# Generated by Django 4.0.1 on 2022-01-20 18:26

from django.db import migrations, models
import watchlist.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[watchlist.validators.MinValueValidator(1.0), watchlist.validators.MaxValueValidator(10.0)])),
                ('votes', models.IntegerField(validators=[watchlist.validators.MinValueValidator(1000), watchlist.validators.MaxValueValidator((2528513,))])),
                ('genre', models.CharField(choices=[('drama', 'Drama'), ('comedy', 'Comedy'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('adventure', 'Adventure'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('musical', 'Musical'), ('western', 'Western'), ('thriller', 'Thriller'), ('crime', 'Crime'), ('war', 'War'), ('animation', 'Animation'), ('fantasy', 'Fantasy'), ('family', 'Family'), ('biography', 'Biography'), ('music', 'Music'), ('action', 'Action'), ('sci-fi', 'Sci-Fi'), ('history', 'History'), ('sport', 'Sport'), ('adult', 'Adult'), ('short', 'Short'), ('news', 'News'), ('talk-show', 'Talk-Show'), ('reality-tv', 'Reality-TV'), ('game-show', 'Game-Show')], max_length=32)),
                ('prod_year', models.IntegerField(validators=[watchlist.validators.MinValueValidator(1960), watchlist.validators.MaxValueValidator(2022)])),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('actress', 'Actress'), ('director', 'Director')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('birth_year', models.IntegerField(validators=[watchlist.validators.MinValueValidator(1900), watchlist.validators.MaxValueValidator(2022)])),
            ],
        ),
    ]
